// Generated by gencpp from file sdf_tools/SDF.msg
// DO NOT EDIT!


#ifndef SDF_TOOLS_MESSAGE_SDF_H
#define SDF_TOOLS_MESSAGE_SDF_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace sdf_tools
{
template <class ContainerAllocator>
struct SDF_
{
  typedef SDF_<ContainerAllocator> Type;

  SDF_()
    : header()
    , serialized_sdf()
    , is_compressed(false)  {
    }
  SDF_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , serialized_sdf(_alloc)
    , is_compressed(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _serialized_sdf_type;
  _serialized_sdf_type serialized_sdf;

   typedef uint8_t _is_compressed_type;
  _is_compressed_type is_compressed;





  typedef boost::shared_ptr< ::sdf_tools::SDF_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sdf_tools::SDF_<ContainerAllocator> const> ConstPtr;

}; // struct SDF_

typedef ::sdf_tools::SDF_<std::allocator<void> > SDF;

typedef boost::shared_ptr< ::sdf_tools::SDF > SDFPtr;
typedef boost::shared_ptr< ::sdf_tools::SDF const> SDFConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sdf_tools::SDF_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sdf_tools::SDF_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sdf_tools

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sdf_tools': ['/home/edmund/test_ws/src/sdf_tools/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sdf_tools::SDF_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sdf_tools::SDF_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sdf_tools::SDF_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sdf_tools::SDF_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdf_tools::SDF_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdf_tools::SDF_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sdf_tools::SDF_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1757aa4e37125d22779ece857cdca208";
  }

  static const char* value(const ::sdf_tools::SDF_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1757aa4e37125d22ULL;
  static const uint64_t static_value2 = 0x779ece857cdca208ULL;
};

template<class ContainerAllocator>
struct DataType< ::sdf_tools::SDF_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sdf_tools/SDF";
  }

  static const char* value(const ::sdf_tools::SDF_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sdf_tools::SDF_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
uint8[] serialized_sdf\n\
bool is_compressed\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::sdf_tools::SDF_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sdf_tools::SDF_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.serialized_sdf);
      stream.next(m.is_compressed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SDF_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sdf_tools::SDF_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sdf_tools::SDF_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "serialized_sdf[]" << std::endl;
    for (size_t i = 0; i < v.serialized_sdf.size(); ++i)
    {
      s << indent << "  serialized_sdf[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.serialized_sdf[i]);
    }
    s << indent << "is_compressed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_compressed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SDF_TOOLS_MESSAGE_SDF_H
